---
- hosts: localhost
  gather_facts: true
  
  vars:
    instance_type: t2.micro
    group_id: sg-f726a090
    image: ami-b0ac25c3
    #count: 1
    keypair: kaushik-dev-2016
    region: eu-west-1

  tasks:
  - name: Launch EC2 instance
    ec2:
       group_id={{ group_id }}
       instance_type={{ instance_type }} 
       image={{ image }}
       wait=true
       keypair={{ keypair }}
       count={{ count }}
       region={{ region }}
       instance_tags:
            name: Dynamic
            Region: Development
    register: ec2
    
  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: ec2.instances
  
- name: Working with new set of hosts 
  hosts: ec2hosts
  gather_facts: true
  
  tasks:
  - name: Ping the servers
    action: ping
    register: ec2_ping